### ISSUE TITLE
can't search image

### ISSUE THREAD

**Issue by tengshan2008** [vicanso/diving#1]
first into web is ok. input the image's name and enter search, it is broken.

say: Cannot read property 'trim' of undefined

**Comment by vicanso** [comment]
Please tell me the image's name you input. Or you can try to input `redis` and see whether it's ok.

**Comment by Baiyuetribe** [comment]
I am the same。No matter what I type to search, it is broken. "say: Cannot read property 'trim' of undefined".
I am using docker deployment locally, and it is the problem.

**Comment by vicanso** [comment]
@Baiyuetribe  Could you show me the browser version?

**Comment by vicanso** [comment]
@tengshan2008 @Baiyuetribe  It has been fixed.
